name: 'BNVD CVE Enricher'
description: 'Busca alertas do Dependabot e CodeQL e enriquece CVEs usando o BNVD.'
author: 'BNVD Team'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  github_token:
    description: 'Token do GitHub para acessar APIs de segurança.'
    required: true
  bnvd_api_url:
    description: 'URL da API do BNVD.'
    required: false
    default: 'https://bnvd.org.br/api/v1'
  include_translations:
    description: 'Inclui traduções em PT-BR.'
    required: false
    default: 'true'
  severity_filter:
    description: 'Filtro de severidade.'
    required: false
    default: 'ALL'

outputs:
  total_cves_found:
    value: ${{ steps.run-enrichment.outputs.total_cves_found }}
  enriched_cves:
    value: ${{ steps.run-enrichment.outputs.enriched_cves }}
  report_file:
    value: ${{ steps.run-enrichment.outputs.report_file }}
  cve_details:
    value: ${{ steps.run-enrichment.outputs.cve_details }}

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: pip install -r requirements.txt

    - name: Run Enrichment Script
      id: run-enrichment
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_BNVD_API_URL: ${{ inputs.bnvd_api_url }}
        INPUT_INCLUDE_TRANSLATIONS: ${{ inputs.include_translations }}
        INPUT_SEVERITY_FILTER: ${{ inputs.severity_filter }}

        # Agora funcionando
        GITHUB_REPOSITORY: ${{ github.repository }}
        GITHUB_WORKSPACE: ${{ github.workspace }}
        GITHUB_OUTPUT: ${{ github.output }}
      run: python src/main.py
