name: "BNVD Security Enricher"
description: "Recebe JSONs de alertas (CodeQL + Dependabot), extrai CVEs, consulta BNVD API v1 e gera relatório."
author: "BNVD.org - Juan Mathews"

inputs:
  codeql_path:
    description: "Caminho para codeql_alerts.json (no workspace). Se vazio, tenta $GITHUB_WORKSPACE/codeql_alerts.json"
    required: false
    default: ""
  dependabot_path:
    description: "Caminho para dependabot_alerts.json (no workspace). Se vazio, tenta $GITHUB_WORKSPACE/dependabot_alerts.json"
    required: false
    default: ""
  include_pt:
    description: "Incluir traduções em pt (true/false)"
    required: false
    default: "true"

outputs:
  total_cves:
    description: "Número total de CVEs extraídas"
  report_file:
    description: "Caminho do relatório JSON gerado (bnvd_security_report.json)"
  bnvd_report:
    description: "Relatório BNVD (json string compacta)"

runs:
  using: "composite"
  steps:
    - name: Ensure jq/curl available
      shell: bash
      run: |
        apt-get update -y && apt-get install -y jq curl >/dev/null || true

    - name: Resolve input paths
      id: resolve_paths
      shell: bash
      run: |
        CODEQL_PATH="${{ inputs.codeql_path }}"
        DEPENDABOT_PATH="${{ inputs.dependabot_path }}"

        if [ -z "$CODEQL_PATH" ]; then
          CODEQL_PATH="$GITHUB_WORKSPACE/codeql_alerts.json"
        fi
        if [ -z "$DEPENDABOT_PATH" ]; then
          DEPENDABOT_PATH="$GITHUB_WORKSPACE/dependabot_alerts.json"
        fi

        echo "codeql_path=$CODEQL_PATH" >> $GITHUB_OUTPUT
        echo "dependabot_path=$DEPENDABOT_PATH" >> $GITHUB_OUTPUT

    - name: Validate inputs files
      shell: bash
      run: |
        if [ ! -f "${{ steps.resolve_paths.outputs.codeql_path }}" ]; then
          echo "{}" > "${{ steps.resolve_paths.outputs.codeql_path }}"
        fi
        if [ ! -f "${{ steps.resolve_paths.outputs.dependabot_path }}" ]; then
          echo "{}" > "${{ steps.resolve_paths.outputs.dependabot_path }}"
        fi

    - name: Extract unique CVEs
      id: extract
      shell: bash
      run: |
        CODEQL="${{ steps.resolve_paths.outputs.codeql_path }}"
        DEP="${{ steps.resolve_paths.outputs.dependabot_path }}"

        # Extrai CVEs de security_advisory.identifiers (cada item pode ter vários identificadores)
        jq -r '
          (.[].security_advisory.identifiers[]? | select(.type=="CVE") | .value)
        ' "$CODEQL" 2>/dev/null || true > /tmp/codeql_cves_raw.txt

        jq -r '
          (.[].security_advisory.identifiers[]? | select(.type=="CVE") | .value)
        ' "$DEP" 2>/dev/null || true > /tmp/dep_cves_raw.txt

        cat /tmp/codeql_cves_raw.txt /tmp/dep_cves_raw.txt | grep -E '^CVE-' || true | sort -u > /tmp/cves.txt

        TOTAL=$(wc -l < /tmp/cves.txt || true)
        echo "total_cves=$TOTAL" >> $GITHUB_OUTPUT
        echo "cves_file=/tmp/cves.txt" >> $GITHUB_OUTPUT

    - name: Query BNVD API for each CVE
      id: query_bnvd
      shell: bash
      run: |
        INCLUDE_PT="${{ inputs.include_pt }}"
        OUT="bnvd_results.json"
        echo "[]" > $OUT

        if [ -s /tmp/cves.txt ]; then
          while read -r CVE; do
            echo "Query BNVD $CVE"
            RES=$(curl -s "https://bnvd.org/api/v1/vulnerabilities/${CVE}?include_pt=${INCLUDE_PT}")
            # Se retorno vazio ou erro, cria objeto de erro
            if [ -z "$RES" ] || [ "$RES" = "null" ]; then
              RES='{"status":"error","message":"no data"}'
            fi
            # Append
            jq --argjson new "$RES" '. += [$new]' $OUT > tmp.$$.json && mv tmp.$$.json $OUT
          done < /tmp/cves.txt
        fi

        echo "report_file=$GITHUB_WORKSPACE/bnvd_security_report.json" >> $GITHUB_OUTPUT
        jq -n \
          --argjson codeql "$(jq -c '.' "${{ steps.resolve_paths.outputs.codeql_path }}" 2>/dev/null || echo '{}')" \
          --argjson dependabot "$(jq -c '.' "${{ steps.resolve_paths.outputs.dependabot_path }}" 2>/dev/null || echo '{}')" \
          --argfile bnvd $OUT \
          '{
            codeql_alerts: $codeql,
            dependabot_alerts: $dependabot,
            bnvd: $bnvd
          }' > $GITHUB_WORKSPACE/bnvd_security_report.json

        # compact json as output
        BNVD_COMP=$(jq -c '.' $GITHUB_WORKSPACE/bnvd_security_report.json)
        echo "bnvd_report=$BNVD_COMP" >> $GITHUB_OUTPUT
