name: 'BNVD CVE Enricher'
description: 'Busca alertas de segurança do Dependabot e CodeQL, e enriquece os CVEs encontrados com dados em português do BNVD.'
author: 'BNVD Team'

branding:
  icon: 'shield'
  color: 'blue'

inputs:
  github_token:
    description: 'Token do GitHub para acessar as APIs de segurança. Use `secrets.GITHUB_TOKEN`.'
    required: true
  bnvd_api_url:
    description: 'URL da API do BNVD.'
    required: false
    default: 'https://bnvd.org.br/api/v1'
  include_translations:
    description: 'Define se as descrições em português devem ser incluídas no relatório.'
    required: false
    default: 'true'
  severity_filter:
    description: 'Filtra alertas por severidade (LOW, MEDIUM, HIGH, CRITICAL, ALL).'
    required: false
    default: 'ALL'

outputs:
  total_cves_found:
    description: 'O número total de alertas com CVEs encontrados (Dependabot e CodeQL).'
  enriched_cves:
    description: 'O número de CVEs que foram enriquecidos com dados do BNVD e passaram no filtro de severidade.'
  report_file:
    description: 'O caminho para o arquivo de relatório Markdown gerado (ex: bnvd-security-report.md).'
  cve_details:
    description: 'Uma string JSON com um resumo dos CVEs enriquecidos.'

runs:
  using: 'composite'
  steps:
    - name: Setup Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      shell: bash
      working-directory: ${{ github.action_path }}
      run: pip install -r requirements.txt

    - name: Run Enrichment Script
      id: run-enrichment
      shell: python
      working-directory: ${{ github.action_path }}
      env:
        # Pass inputs to the script as environment variables
        INPUT_GITHUB_TOKEN: ${{ inputs.github_token }}
        INPUT_BNVD_API_URL: ${{ inputs.bnvd_api_url }}
        INPUT_INCLUDE_TRANSLATIONS: ${{ inputs.include_translations }}
        INPUT_SEVERITY_FILTER: ${{ inputs.severity_filter }}
        GITHUB_REPOSITORY: ${{ github.repository }}
      run: src/main.py

